export const GET_ALL_DRIVERS = "GET_ALL_DRIVERS";
export const GET_DRIVERS_BY_NAME = "GET_DRIVERS_BY_NAME";
export const GET_DRIVER_DETAIL = "GET_DRIVER_DETAIL";
export const CLEAR_DRIVER_DETAIL = "CLEAR_DRIVER_DETAIL";
export const GET_ALL_TEAMS = "GET_ALL_TEAMS";
export const FILTER_DRIVERS = "FILTER_DRIVERS";
export const ORDER_DRIVERS = "ORDER_DRIVERS";
